IMporter

diff --git a/.github/workflows/import.yml b/.github/workflows/import.yml
--- a/.github/workflows/import.yml
+++ b/.github/workflows/import.yml
@@ -15,13 +15,6 @@ jobs:
       env:
         KARM_QUAY_API_TOKEN: ${{ secrets.KARM_QUAY_API_TOKEN }}
       run: |
-        # https://github.com/orgs/community/discussions/148648
-        for var in PATH XDG_CONFIG_HOME; do
-            sed -Ee "s/^/${var}=/" -e 's/(runner)admin/\1/g' <<< "${!var}"
-        done | tee -a "$GITHUB_ENV"
-        ln -s /home/runner /home/runneradmin
-        sudo apt-get install -y podman
-
         mkdir ~/.docker -p
         tee ~/.docker/config.json <<-EOX
         {
@@ -65,10 +58,10 @@ jobs:
           tag=$(echo $image | cut -d':' -f2)
           new_image="quay.io/$quay_user/$(echo $image | cut -d'/' -f2- | cut -d':' -f1):$tag"
           echo "Pulling $image..."
-          podman pull $image || { echo "Failed to pull $image"; continue; }
+          docker pull $image || { echo "Failed to pull $image"; continue; }
           echo "Tagging $image to $new_image..."
-          podman tag $image $new_image || { echo "Failed to tag image"; continue; }
+          docker tag $image $new_image || { echo "Failed to tag image"; continue; }
           echo "Pushing $new_image to Quay.io..."
-          podman push $new_image || { echo "Failed to push $new_image"; continue; }
+          docker push $new_image || { echo "Failed to push $new_image"; continue; }
           echo "--------------------"
         done
